
project_id = "mzbadxfvxioedzdjxamc"

[functions.send-email]
verify_jwt = false
[functions.ai-chat]
verify_jwt = false
[functions.push-notify]
verify_jwt = false
[functions.auth-guard]
verify_jwt = false
[functions.admin-verify]
verify_jwt = false
