
project_id = "mzbadxfvxioedzdjxamc"

[functions.uniplaces-proxy]
verify_jwt = false

[functions.send-email]
verify_jwt = false
[functions.ai-chat]
verify_jwt = false
[functions.push-notify]
verify_jwt = false
[functions.auth-guard]
verify_jwt = false
[functions.admin-verify]
verify_jwt = false
[functions.create-influencer]
verify_jwt = false
[functions.get-exchange-rate]
verify_jwt = false
[functions.create-team-member]
verify_jwt = false
[functions.send-custom-notification]
verify_jwt = false
